include $(CLEAR_VARS)
LOCAL_WHOLE_STATIC_LIBRARES := libqdMetaData
LOCAL_MODULE := libqdMetaData.system_ext
LOCAL_INSTALLED_MODULE_STEM := libqdMetaData.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SYSTEM_EXT_MODULE := true
include $(BUILD_SHARED_LIBRARY)
